header:
  license:
    spdx-id: Apache-2.0

  paths-ignore:
    - '.venv'
    - '.github'
    - 'node_modules'
    - 'docs'
    - 'assets'
    - 'marketing'
    - '*.md'
    - '*.txt'
    - '*.json'
    - '*.yaml'
    - '*.yml'
    - '*.toml'
    - '*.cfg'
    - '*.lock'
    - 'k8s'
    - 'LICENSE'
    - '.gitignore'
    - '.env.example'
    - '.env'

  comment: on-failure
