header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: The Migratowl Authors
    software-name: Migratowl

  paths-ignore:
    - '.venv'
    - '.github'
    - 'node_modules'
    - 'docs'
    - 'assets'
    - 'marketing'
    - '*.md'
    - '*.txt'
    - '*.json'
    - '*.yaml'
    - '*.yml'
    - '*.toml'
    - '*.cfg'
    - '*.lock'
    - 'k8s'

  comment: on-failure
